{{ config(
    materialized='table',
    schema='MARTS',
    tags=['dimensions', 'repositories'],
    meta={
        'owner': 'Data Engineering',
        'description': 'GitHub repository dimension table'
    }
) }}

-- Dimension: GitHub Repositories
-- Type 1 SCD (no history tracking)
-- Source: stg_repositories (from stg_github_events)
-- Grain: One row per repository
-- Surrogate Key: repo_key (generated by dbt)

WITH repo_staging AS (
  SELECT 
    repo_id,
    repo_name,
    repo_owner,
    repo_short_name,
    first_event_at,
    last_event_at,
    days_active
  FROM {{ ref('stg_repositories') }}
)

SELECT 
  {{ dbt_utils.generate_surrogate_key(['repo_id']) }} as repo_key,
  repo_id,
  repo_name,
  repo_owner,
  repo_short_name,
  first_event_at,
  last_event_at,
  days_active,
  CASE 
    WHEN repo_name ILIKE '%test%' OR repo_name ILIKE '%example%' THEN true 
    ELSE false 
  END as is_test_repo,
  CURRENT_TIMESTAMP() as dbt_created_at,
  CURRENT_TIMESTAMP() as dbt_updated_at
FROM repo_staging
WHERE repo_id IS NOT NULL
  AND repo_name IS NOT NULL
