{{ config(
    materialized='table',
    schema='MARTS',
    tags=['dimensions', 'event-types'],
    meta={
        'owner': 'Data Engineering',
        'description': 'GitHub event type dimension table'
    }
) }}

-- Dimension: GitHub Event Types
-- Type 1 SCD (static dimension)
-- Source: stg_event_types (enumeration of all event types)
-- Grain: One row per event type
-- Surrogate Key: event_type_key (generated by dbt)

WITH event_types AS (
  SELECT 
    event_type,
    event_count,
    unique_actors,
    unique_repos,
    first_occurrence,
    last_occurrence,
    percent_of_total_events,
    event_description
  FROM {{ ref('stg_event_types') }}
)

SELECT 
  {{ dbt_utils.generate_surrogate_key(['event_type']) }} as event_type_key,
  event_type,
  event_description,
  event_count,
  unique_actors,
  unique_repos,
  percent_of_total_events,
  first_occurrence,
  last_occurrence,
  CASE 
    WHEN event_type IN ('PushEvent', 'PullRequestEvent', 'IssuesEvent') THEN 'Activity'
    WHEN event_type IN ('CreateEvent', 'DeleteEvent') THEN 'Repository Management'
    WHEN event_type IN ('WatchEvent', 'ForkEvent') THEN 'Engagement'
    WHEN event_type IN ('MemberEvent', 'ReleaseEvent') THEN 'Collaboration'
    ELSE 'Other'
  END as event_category,
  CURRENT_TIMESTAMP() as dbt_created_at,
  CURRENT_TIMESTAMP() as dbt_updated_at
FROM event_types
WHERE event_type IS NOT NULL
